# Generated by Django 2.1.2 on 2018-10-29 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf', models.CharField(default='222', max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(default='0101', max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('unit_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('units', models.IntegerField(default=0)),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapper.Lecturer')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapper.Student')),
            ],
        ),
    ]
