# Generated by Django 2.1.2 on 2018-10-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
