# Generated by Django 2.1.2 on 2018-10-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_lecturer_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
